### PR TITLE
fix: TOB-ZKTRIE-19 Unchecked usize to c_int casts allow hash collisions

### PR DESCRIPTION
**Pull request by vyzo**
Open question: is this function even used by anything other than tests?
If so we should update the callers, but I haven't found any in the repo.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205044772140417

### CODE REVIEW

**Review by noel2004 — COMMENTED** [review]
This PR change the return of `parse` in `ZkTrieNode` while there are several calling in zkevm-circuit side on it, [like here](https://github.com/scroll-tech/zkevm-circuits/blob/9b46ddbf01393ad845e48dea77de55b9358074da/zktrie/src/state/witness.rs#L469). All of these calling code need to be updated.

Also, in the common scene (it is used for handling the passing l2trace data), the size of input data should be highly impossible to exceed `c_int::MAX`. Or say, this method is never designed for datas larger than such a huge size. So maybe we can simply panic for int casting inside the method instead of throw it out?

**Comment by vyzo** [comment]
Yeah, i guess we could just unwrap and avoid the interface change.

@Thegaram are we ok with yet another panic point?

**Comment by Thegaram** [comment]
> Yeah, i guess we could just unwrap and avoid the interface change.
> 
> @Thegaram are we ok with yet another panic point?

Sounds good to me, we can try to eliminate these later during a major refactor.

**Comment by vyzo** [comment]
Rebased and updated so that it doesn't change the interface, as discussed.

**Review by noel2004 — APPROVED** [review]

**Pull request merged**
